# Generated by Django 4.1.2 on 2022-10-18 03:51

from django.db import migrations, models
import xicheba.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cashier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('incoming', '收入'), ('outgoing', '支出')], max_length=10, verbose_name='记账类型')),
                ('number', models.IntegerField(default=0, help_text='自动记数到材料管理', verbose_name='数量')),
                ('price_type', models.CharField(choices=[('original_price', '原价'), ('price', '售价'), ('discount_price', '折扣价')], help_text='记账类型为支出请选择: 原价 < ฅʕ•̫͡•ʔฅ > 记账类型为收入请选择：售价或者折扣价', max_length=20, verbose_name='价格类型')),
                ('money', models.IntegerField(default=0, help_text='总价格自动计算', verbose_name='总金额')),
                ('remarks', models.CharField(blank=True, help_text='100字以内的备注内容', max_length=100, null=True, verbose_name='备注')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '出纳明细',
                'verbose_name_plural': '出纳管理',
            },
            bases=(models.Model, xicheba.models.ToolsBox),
        ),
        migrations.CreateModel(
            name='ExtraProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(default=0, verbose_name='次数')),
                ('money', models.IntegerField(default=0, verbose_name='总金额')),
                ('remarks', models.CharField(blank=True, help_text='100字以内的备注内容', max_length=100, null=True, verbose_name='备注')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '散项明细',
                'verbose_name_plural': '散项管理',
            },
            bases=(models.Model, xicheba.models.ToolsBox),
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='客户名称')),
                ('sex', models.CharField(choices=[('G', '男'), ('M', '女')], default='G', max_length=1, verbose_name='客户性别')),
                ('user_level', models.CharField(choices=[('member', '会员'), ('not_member', '非会员')], default='not_member', max_length=10, verbose_name='客户等级')),
                ('phone_number', models.CharField(blank=True, max_length=11, null=True, verbose_name='手机号码')),
                ('make_collections', models.IntegerField(default=0, verbose_name='已收会员款')),
                ('payment_methods', models.CharField(choices=[('alipay', '支付宝'), ('wechat', '微信'), ('rmb', '现金')], default='wechat', max_length=10, verbose_name='支付方式')),
                ('member_frequency', models.IntegerField(default=0, verbose_name='会员价洗车次数')),
                ('using_frequency', models.IntegerField(default=0, help_text='每消费一次加一', verbose_name='消费次数')),
                ('remarks', models.CharField(blank=True, help_text='100字以内的备注内容', max_length=100, null=True, verbose_name='备注')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '客户明细',
                'verbose_name_plural': '客户管理',
            },
            bases=(models.Model, xicheba.models.ToolsBox),
        ),
    ]
