# Generated by Django 4.1.2 on 2022-10-18 03:52

from django.db import migrations, models
import xicheba.models


class Migration(migrations.Migration):

    dependencies = [
        ('xicheba', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='事件类型')),
                ('remarks', models.CharField(blank=True, help_text='100字以内的备注内容', max_length=100, null=True, verbose_name='备注')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '事件明细',
                'verbose_name_plural': '事件管理',
            },
            bases=(models.Model, xicheba.models.ToolsBox),
        ),
    ]
