# Generated by Django 4.1.2 on 2022-10-18 03:53

from django.db import migrations, models
import xicheba.models


class Migration(migrations.Migration):

    dependencies = [
        ('xicheba', '0002_eventtype'),
    ]

    operations = [
        migrations.CreateModel(
            name='Materials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15, verbose_name='材料名')),
                ('specifications', models.CharField(blank=True, max_length=15, null=True, verbose_name='规格')),
                ('original_price', models.IntegerField(default=0, verbose_name='原价')),
                ('price', models.IntegerField(default=0, verbose_name='售价')),
                ('discount_price', models.IntegerField(default=0, verbose_name='折扣价')),
                ('number', models.IntegerField(default=0, help_text='由出纳管理自动记数', verbose_name='数量')),
                ('brand', models.CharField(blank=True, max_length=10, verbose_name='品牌名')),
                ('functions_and_performance', models.CharField(blank=True, max_length=20, null=True, verbose_name='功能')),
                ('remarks', models.CharField(blank=True, help_text='100字以内的备注内容', max_length=100, null=True, verbose_name='备注')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '材料明细',
                'verbose_name_plural': '材料管理',
            },
            bases=(models.Model, xicheba.models.ToolsBox),
        ),
        migrations.AddField(
            model_name='extraproject',
            name='action',
            field=models.CharField(choices=[], default='', max_length=30, verbose_name='事件类型'),
        ),
    ]
