# Generated by Django 4.1.2 on 2022-10-18 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xicheba', '0003_materials_extraproject_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashier',
            name='name',
            field=models.CharField(choices=[], default='', max_length=30, verbose_name='物品名称'),
        ),
    ]
