# Generated by Django 4.1.2 on 2022-10-19 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xicheba', '0005_alter_cashier_id_alter_cashier_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashier',
            name='id',
            field=models.BigIntegerField(primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
