# Generated by Django 4.1.2 on 2022-10-19 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xicheba', '0006_alter_cashier_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashier',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
