# Generated by Django 4.1.2 on 2022-10-19 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xicheba', '0007_alter_cashier_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventtype',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='extraproject',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='materials',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='users',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
