# Generated by Django 4.1.2 on 2022-10-19 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xicheba', '0009_cashier_earnings_alter_cashier_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashier',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='逻辑删除'),
        ),
        migrations.AlterField(
            model_name='cashier',
            name='id',
            field=models.BigAutoField(help_text='自动增长', primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='cashier',
            name='name',
            field=models.CharField(choices=[('4-CL', '4-车蜡'), ('5-BLS', '5-玻璃水')], default='', max_length=30, verbose_name='物品名称'),
        ),
        migrations.AlterField(
            model_name='eventtype',
            name='id',
            field=models.BigAutoField(help_text='自动增长', primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='extraproject',
            name='action',
            field=models.CharField(choices=[('1-DL', '1-打蜡'), ('2-JD', '2-脚垫'), ('3-CZ', '3-车座'), ('4-PG', '4-抛光'), ('5-SF', '5-水费'), ('6-DF', '6-电费'), ('7-TM', '7-贴膜')], default='', max_length=30, verbose_name='事件类型'),
        ),
        migrations.AlterField(
            model_name='extraproject',
            name='id',
            field=models.BigAutoField(help_text='自动增长', primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='materials',
            name='id',
            field=models.BigAutoField(help_text='自动增长', primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='users',
            name='id',
            field=models.BigAutoField(help_text='自动增长', primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
