# Generated by Django 4.1.2 on 2022-10-19 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xicheba', '0011_users_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='extraproject',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='逻辑删除'),
        ),
    ]
