# Generated by Django 4.1.2 on 2022-10-20 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xicheba', '0013_remove_cashier_is_deleted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashier',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='逻辑删除'),
        ),
    ]
