# Generated by Django 4.1.2 on 2022-10-20 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xicheba', '0014_cashier_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashier',
            name='create_by_user',
            field=models.CharField(default='no_user', max_length=20, verbose_name='创建用户'),
        ),
    ]
