# Generated by Django 4.1.2 on 2022-10-20 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xicheba', '0017_alter_cashier_create_by_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashier',
            name='create_by_user',
            field=models.IntegerField(default='0', verbose_name='创建用户'),
        ),
    ]
