# Generated by Django 4.1.2 on 2022-10-20 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xicheba', '0019_users_create_by_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='逻辑删除'),
        ),
    ]
