# Generated by Django 4.1.2 on 2022-10-20 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xicheba', '0020_users_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='extraproject',
            name='create_by_user',
            field=models.IntegerField(default='0', verbose_name='创建用户'),
        ),
        migrations.AddField(
            model_name='extraproject',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='逻辑删除'),
        ),
    ]
